/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.personManager;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.HomeAddress;
import model.Person;
import model.PersonDirectory;
import model.WorkAddress;

/**
 *
 * @author purka
 */
public class CreatePersonJPanel extends javax.swing.JPanel {
    
    private PersonDirectory persons;
    private JPanel userProcessContainer;

    /**
     * Creates new form CreatePersonJPanel
     * @param persons
     * @param userProcessContainer
     */
    public CreatePersonJPanel(PersonDirectory persons, JPanel userProcessContainer) {
        initComponents();
        
        this.persons = persons;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateTitle = new javax.swing.JLabel();
        personInfoSeparator = new javax.swing.JSeparator();
        homeAddSeparator = new javax.swing.JSeparator();
        lblWorkAdd = new javax.swing.JLabel();
        lblWrkStreetAdd = new javax.swing.JLabel();
        txtWrkStreetAdd = new javax.swing.JTextField();
        txtWrkUnit = new javax.swing.JTextField();
        lblWrkUnit = new javax.swing.JLabel();
        lblWrkZip = new javax.swing.JLabel();
        txtWrkZip = new javax.swing.JTextField();
        lblWrkCity = new javax.swing.JLabel();
        txtWrkCity = new javax.swing.JTextField();
        lblWrkPhoneNum = new javax.swing.JLabel();
        txtWrkPhoneNum = new javax.swing.JTextField();
        lblWrkState = new javax.swing.JLabel();
        txtWrkState = new javax.swing.JTextField();
        txtHmZip = new javax.swing.JTextField();
        txtHmUnit = new javax.swing.JTextField();
        txtHmStreetAdd = new javax.swing.JTextField();
        txtHmCity = new javax.swing.JTextField();
        txtHmState = new javax.swing.JTextField();
        txtHmPhoneNum = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblPersonInfo = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblHomeAdd = new javax.swing.JLabel();
        lblHmStreetAdd = new javax.swing.JLabel();
        lblHmUnit = new javax.swing.JLabel();
        lblHmZip = new javax.swing.JLabel();
        lblHmCity = new javax.swing.JLabel();
        lblHmPhoneNum = new javax.swing.JLabel();
        lblHmState = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        lblErrFirstName = new javax.swing.JLabel();
        lblErrLastName = new javax.swing.JLabel();
        lblErrSsn = new javax.swing.JLabel();
        lblErrAge = new javax.swing.JLabel();
        lblErrHmStAdd = new javax.swing.JLabel();
        lblErrHmUnit = new javax.swing.JLabel();
        lblErrHmCity = new javax.swing.JLabel();
        lblErrHmState = new javax.swing.JLabel();
        lblErrWrkStAdd = new javax.swing.JLabel();
        lblErrWrkUnit = new javax.swing.JLabel();
        lblErrWrkCity = new javax.swing.JLabel();
        lblErrHmZip = new javax.swing.JLabel();
        lblErrHmPhone = new javax.swing.JLabel();
        lblErrWrkState = new javax.swing.JLabel();
        lblErrWrkZip = new javax.swing.JLabel();
        lblErrWrkPhone = new javax.swing.JLabel();

        lblCreateTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateTitle.setText("CREATE A PERSON PROFILE");

        lblWorkAdd.setText("WORK ADDRESS");

        lblWrkStreetAdd.setText("STREET ADDRESS");

        txtWrkStreetAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtWrkStreetAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWrkStreetAddKeyReleased(evt);
            }
        });

        txtWrkUnit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtWrkUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWrkUnitKeyReleased(evt);
            }
        });

        lblWrkUnit.setText("UNIT");

        lblWrkZip.setText("ZIP CODE");

        txtWrkZip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtWrkZip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWrkZipKeyReleased(evt);
            }
        });

        lblWrkCity.setText("CITY");

        txtWrkCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtWrkCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWrkCityKeyReleased(evt);
            }
        });

        lblWrkPhoneNum.setText("PHONE NUMBER");

        txtWrkPhoneNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtWrkPhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWrkPhoneNumKeyReleased(evt);
            }
        });

        lblWrkState.setText("STATE");

        txtWrkState.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtWrkState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWrkStateKeyReleased(evt);
            }
        });

        txtHmZip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtHmZip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHmZipKeyReleased(evt);
            }
        });

        txtHmUnit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtHmUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHmUnitKeyReleased(evt);
            }
        });

        txtHmStreetAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtHmStreetAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHmStreetAddKeyReleased(evt);
            }
        });

        txtHmCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtHmCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHmCityKeyReleased(evt);
            }
        });

        txtHmState.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtHmState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHmStateKeyReleased(evt);
            }
        });

        txtHmPhoneNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtHmPhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHmPhoneNumKeyReleased(evt);
            }
        });

        txtSsn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtSsn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSsnKeyReleased(evt);
            }
        });

        txtFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
        });

        txtLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameKeyReleased(evt);
            }
        });

        txtAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });

        lblPersonInfo.setText("PERSONAL INFORMATION");

        lblFirstName.setText("FIRST NAME");

        lblSsn.setText("SSN");

        lblLastName.setText("LAST NAME");

        lblAge.setText("AGE");

        lblHomeAdd.setText("HOME ADDRESS");

        lblHmStreetAdd.setText("STREET ADDRESS");

        lblHmUnit.setText("UNIT");

        lblHmZip.setText("ZIP CODE");

        lblHmCity.setText("CITY");

        lblHmPhoneNum.setText("PHONE NUMBER");

        lblHmState.setText("STATE");

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/icons/create.png"))); // NOI18N
        btnCreate.setText("Create");
        btnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblErrFirstName.setForeground(new java.awt.Color(255, 0, 51));

        lblErrLastName.setForeground(new java.awt.Color(255, 0, 51));

        lblErrSsn.setForeground(new java.awt.Color(255, 0, 51));

        lblErrAge.setForeground(new java.awt.Color(255, 0, 51));

        lblErrHmStAdd.setForeground(new java.awt.Color(255, 0, 51));

        lblErrHmUnit.setForeground(new java.awt.Color(255, 0, 51));

        lblErrHmCity.setForeground(new java.awt.Color(255, 0, 51));

        lblErrHmState.setForeground(new java.awt.Color(255, 0, 51));

        lblErrWrkStAdd.setForeground(new java.awt.Color(255, 0, 51));

        lblErrWrkUnit.setForeground(new java.awt.Color(255, 0, 51));

        lblErrWrkCity.setForeground(new java.awt.Color(255, 0, 51));

        lblErrHmZip.setForeground(new java.awt.Color(255, 0, 51));

        lblErrHmPhone.setForeground(new java.awt.Color(255, 0, 51));

        lblErrWrkState.setForeground(new java.awt.Color(255, 0, 51));

        lblErrWrkZip.setForeground(new java.awt.Color(255, 0, 0));

        lblErrWrkPhone.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreateTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblWorkAdd)
                            .addComponent(lblHomeAdd)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPersonInfo)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblWrkStreetAdd)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblWrkUnit)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtWrkUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblWrkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtWrkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblWrkState, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(12, 12, 12)
                                                    .addComponent(lblErrWrkUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(63, 63, 63)
                                                    .addComponent(lblErrWrkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtWrkState, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblErrWrkState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(5, 5, 5))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblWrkZip)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblErrWrkZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtWrkZip, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblWrkPhoneNum)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblErrWrkPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtWrkPhoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(personInfoSeparator, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblHmUnit)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblErrHmUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtHmUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblHmCity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblErrHmCity, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtHmCity, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblHmZip)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(lblErrHmZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(txtHmZip, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblHmPhoneNum)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblHmState, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblErrHmState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(txtHmState)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtHmPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 1, Short.MAX_VALUE))
                                                    .addComponent(lblErrHmPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblHmStreetAdd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblErrHmStAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtHmStreetAdd)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblFirstName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblErrFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(lblLastName)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(14, 14, 14)
                                                        .addComponent(lblErrLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtLastName))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblSsn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblErrSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblAge)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblErrAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(homeAddSeparator)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrWrkStAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWrkStreetAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(btnCreate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCreateTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPersonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrFirstName)
                    .addComponent(lblErrLastName))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsn)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrSsn)
                    .addComponent(lblErrAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personInfoSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHomeAdd)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHmStreetAdd)
                    .addComponent(txtHmStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblErrHmStAdd)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHmCity)
                            .addComponent(txtHmCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHmState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHmState))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblErrHmUnit)
                            .addComponent(lblErrHmCity)
                            .addComponent(lblErrHmState))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHmZip)
                            .addComponent(txtHmZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHmPhoneNum)
                            .addComponent(txtHmPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHmUnit)
                        .addComponent(txtHmUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrHmZip)
                    .addComponent(lblErrHmPhone))
                .addGap(18, 18, 18)
                .addComponent(homeAddSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWorkAdd)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWrkStreetAdd)
                            .addComponent(txtWrkStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(lblErrWrkStAdd)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWrkUnit)
                            .addComponent(txtWrkUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWrkCity)
                            .addComponent(txtWrkCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWrkState)
                            .addComponent(txtWrkState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblErrWrkCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrWrkUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblErrWrkState, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWrkZip)
                    .addComponent(txtWrkZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWrkPhoneNum)
                    .addComponent(txtWrkPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrWrkZip)
                    .addComponent(lblErrWrkPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 29, Short.MAX_VALUE)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
         if (!validateFormFields()) {
             return;
         }
         
         Person person = new Person();
         
         person.setFirstName(txtFirstName.getText());
         person.setLastName(txtLastName.getText());
         person.setSsn(txtSsn.getText());
         try {
             person.setAge(Byte.parseByte(txtAge.getText()));
         } catch(NumberFormatException e) {
           JOptionPane.showMessageDialog(this, 
                "Please check the age input", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return;
         }
         
         if (getHomeAddress() == null) {
             return;
         }
         
         person.setHomeAddress(getHomeAddress());
         
         if (getWorkAddress() == null) {
            return;
         }
         
         person.setWorkAddress(getWorkAddress());
         
         persons.addPerson(person);
         
          JOptionPane.showMessageDialog(this, 
                "Person Successfully Created", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
         
         resetTextFields();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        lblErrFirstName.setText("");
        txtFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyReleased
        lblErrLastName.setText("");
        txtLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtLastNameKeyReleased

    private void txtSsnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSsnKeyReleased
        lblErrSsn.setText("");
        txtSsn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtSsnKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        lblErrAge.setText("");
        txtAge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtHmStreetAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHmStreetAddKeyReleased
        lblErrHmStAdd.setText("");
        txtHmStreetAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtHmStreetAddKeyReleased

    private void txtHmUnitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHmUnitKeyReleased
        lblErrHmUnit.setText("");
        txtHmUnit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtHmUnitKeyReleased

    private void txtHmCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHmCityKeyReleased
        lblErrHmCity.setText("");
        txtHmCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtHmCityKeyReleased

    private void txtHmStateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHmStateKeyReleased
        lblErrHmState.setText("");
        txtHmState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtHmStateKeyReleased

    private void txtHmZipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHmZipKeyReleased
        lblErrHmZip.setText("");
        txtHmZip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtHmZipKeyReleased

    private void txtHmPhoneNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHmPhoneNumKeyReleased
        lblErrHmPhone.setText("");
        txtHmPhoneNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtHmPhoneNumKeyReleased

    private void txtWrkStreetAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWrkStreetAddKeyReleased
        lblErrWrkStAdd.setText("");
        txtWrkStreetAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtWrkStreetAddKeyReleased

    private void txtWrkUnitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWrkUnitKeyReleased
        lblErrWrkUnit.setText("");
        txtWrkUnit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtWrkUnitKeyReleased

    private void txtWrkCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWrkCityKeyReleased
        lblErrWrkCity.setText("");
        txtWrkCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtWrkCityKeyReleased

    private void txtWrkStateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWrkStateKeyReleased
        lblErrWrkState.setText("");
        txtWrkState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtWrkStateKeyReleased

    private void txtWrkZipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWrkZipKeyReleased
        lblErrWrkZip.setText("");
        txtWrkZip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtWrkZipKeyReleased

    private void txtWrkPhoneNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWrkPhoneNumKeyReleased
        lblErrWrkPhone.setText("");
        txtWrkPhoneNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, false));
    }//GEN-LAST:event_txtWrkPhoneNumKeyReleased

    private boolean validateFormFields() {
        if (txtFirstName.getText().isBlank()
                && txtWrkZip.getText().isBlank()
                && txtWrkUnit.getText().isBlank()
                && txtWrkStreetAdd.getText().isBlank()
                && txtWrkState.getText().isBlank()
                && txtWrkPhoneNum.getText().isBlank()
                && txtWrkCity.getText().isBlank()
                && txtHmZip.getText().isBlank()
                && txtHmUnit.getText().isBlank()
                && txtHmPhoneNum.getText().isBlank()
                && txtHmState.getText().isBlank()
                && txtHmCity.getText().isBlank()
                && txtHmStreetAdd.getText().isBlank()
                && txtAge.getText().isBlank()
                && txtSsn.getText().isBlank()
                && txtLastName.getText().isBlank()) {
            lblErrFirstName.setText("Required");
            txtFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrWrkZip.setText("Required");
            txtWrkZip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrWrkStAdd.setText("Required");
            txtWrkStreetAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrWrkState.setText("Required");
            txtWrkState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrWrkCity.setText("Required");
            txtWrkCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrWrkPhone.setText("Required");
            txtWrkPhoneNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrHmZip.setText("Required");
            txtHmZip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrHmUnit.setText("Required");
            txtHmUnit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrHmPhone.setText("Required");
            txtHmPhoneNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrHmState.setText("Required");
            txtHmState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrAge.setText("Required");
            txtAge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrSsn.setText("Required");
            txtSsn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrLastName.setText("Required");
            txtLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrHmCity.setText("Required");
            txtHmCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrWrkUnit.setText("Required");
            txtWrkUnit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            lblErrHmStAdd.setText("Required");
            txtHmStreetAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtFirstName.getText().isBlank()) {
            lblErrFirstName.setText("Required");
            txtFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtLastName.getText().isBlank()) {
            lblErrLastName.setText("Required");
            txtLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtSsn.getText().isBlank()) {
            lblErrSsn.setText("Required");
            txtSsn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtAge.getText().isBlank()) {
            lblErrAge.setText("Required");
            txtAge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtHmStreetAdd.getText().isBlank()) {
            lblErrHmStAdd.setText("Required");
            txtHmStreetAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtHmUnit.getText().isBlank()) {
            lblErrHmUnit.setText("Required");
            txtHmUnit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtHmCity.getText().isBlank()) {
            lblErrHmCity.setText("Required");
            txtHmCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtHmState.getText().isBlank()) {
            lblErrHmState.setText("Required");
            txtHmState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtHmZip.getText().isBlank()) {
            lblErrHmZip.setText("Required");
            txtHmZip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtHmPhoneNum.getText().isBlank()) {
            lblErrHmPhone.setText("Required");
            txtWrkPhoneNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtWrkStreetAdd.getText().isBlank()) {
            lblErrWrkStAdd.setText("Required");
            txtWrkStreetAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
         if (txtWrkUnit.getText().isBlank()) {
            lblErrWrkUnit.setText("Required");
            txtWrkUnit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtWrkCity.getText().isBlank()) {
            lblErrWrkCity.setText("Required");
            txtWrkCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtWrkState.getText().isBlank()) {
            lblErrWrkState.setText("Required");
            txtWrkState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtWrkZip.getText().isBlank()) {
            lblErrWrkZip.setText("Required");
            txtWrkZip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        
        if (txtWrkPhoneNum.getText().isBlank()) {
            lblErrWrkPhone.setText("Required");
            txtWrkPhoneNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, false));
            return false;
        }
        return true;
    }
    
    private void resetTextFields() {
        txtAge.setText("");
        txtFirstName.setText("");
        txtHmCity.setText("");
        txtHmPhoneNum.setText("");
        txtHmState.setText("");
        txtHmStreetAdd.setText("");
        txtHmUnit.setText("");
        txtHmZip.setText("");
        txtLastName.setText("");
        txtSsn.setText("");
        txtWrkCity.setText("");
        txtWrkPhoneNum.setText("");
        txtWrkState.setText("");
        txtWrkStreetAdd.setText("");
        txtWrkUnit.setText("");
        txtWrkZip.setText("");
    }
    
    private HomeAddress getHomeAddress() {
        HomeAddress homeAddress = new HomeAddress();
        homeAddress.setCity(txtHmCity.getText());
        try {
            homeAddress.setPhoneNumber(Long.parseLong(txtHmPhoneNum.getText()));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Please check the phone number input", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return null;
        }
        homeAddress.setState(txtHmState.getText());
        homeAddress.setStreetAddress(txtHmStreetAdd.getText());
        try {
            homeAddress.setUnitNumber(Short.parseShort(txtHmUnit.getText()));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Please check the unit number input", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return null;
        }
        try {
            homeAddress.setZip(Integer.parseInt(txtHmZip.getText()));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Please check the zip code input", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return null;
        }
        return homeAddress;
    }

    private WorkAddress getWorkAddress() {
        WorkAddress workAddress = new WorkAddress();
        workAddress.setCity(txtWrkCity.getText());
        try {
            workAddress.setPhoneNumber(Long.parseLong(txtWrkPhoneNum.getText()));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Please check the phone number input", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return null;
        }
        workAddress.setState(txtWrkState.getText());
        workAddress.setStreetAddress(txtWrkStreetAdd.getText());
        try {
            workAddress.setUnitNumber(Short.parseShort(txtWrkUnit.getText()));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Please check the unit number input", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return null;
        }
        try {
            workAddress.setZip(Integer.parseInt(txtWrkZip.getText()));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Please check the zip code input", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return null;
        }
        return workAddress;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JSeparator homeAddSeparator;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCreateTitle;
    private javax.swing.JLabel lblErrAge;
    private javax.swing.JLabel lblErrFirstName;
    private javax.swing.JLabel lblErrHmCity;
    private javax.swing.JLabel lblErrHmPhone;
    private javax.swing.JLabel lblErrHmStAdd;
    private javax.swing.JLabel lblErrHmState;
    private javax.swing.JLabel lblErrHmUnit;
    private javax.swing.JLabel lblErrHmZip;
    private javax.swing.JLabel lblErrLastName;
    private javax.swing.JLabel lblErrSsn;
    private javax.swing.JLabel lblErrWrkCity;
    private javax.swing.JLabel lblErrWrkPhone;
    private javax.swing.JLabel lblErrWrkStAdd;
    private javax.swing.JLabel lblErrWrkState;
    private javax.swing.JLabel lblErrWrkUnit;
    private javax.swing.JLabel lblErrWrkZip;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHmCity;
    private javax.swing.JLabel lblHmPhoneNum;
    private javax.swing.JLabel lblHmState;
    private javax.swing.JLabel lblHmStreetAdd;
    private javax.swing.JLabel lblHmUnit;
    private javax.swing.JLabel lblHmZip;
    private javax.swing.JLabel lblHomeAdd;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPersonInfo;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblWorkAdd;
    private javax.swing.JLabel lblWrkCity;
    private javax.swing.JLabel lblWrkPhoneNum;
    private javax.swing.JLabel lblWrkState;
    private javax.swing.JLabel lblWrkStreetAdd;
    private javax.swing.JLabel lblWrkUnit;
    private javax.swing.JLabel lblWrkZip;
    private javax.swing.JSeparator personInfoSeparator;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHmCity;
    private javax.swing.JTextField txtHmPhoneNum;
    private javax.swing.JTextField txtHmState;
    private javax.swing.JTextField txtHmStreetAdd;
    private javax.swing.JTextField txtHmUnit;
    private javax.swing.JTextField txtHmZip;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtWrkCity;
    private javax.swing.JTextField txtWrkPhoneNum;
    private javax.swing.JTextField txtWrkState;
    private javax.swing.JTextField txtWrkStreetAdd;
    private javax.swing.JTextField txtWrkUnit;
    private javax.swing.JTextField txtWrkZip;
    // End of variables declaration//GEN-END:variables

}
